import { NgModule } from '@angular/core';
import { BrowserModule } from '@angular/platform-browser';
import { FormsModule } from '@angular/forms';
import { HttpModule } from '@angular/http';
import { HttpClientModule } from '@angular/common/http';
import { RouterModule } from '@angular/router';

import { AppComponent } from './app.component';
import { DashComponent } from './dashboard.component';
import { ProductComponent } from './products/product.component';
import { MyUpperPipe } from './products/myUpper.pipe';
import { AddValue } from './products/addValue.pipe';
import { ProductFilter } from './products/productFilter.pipe';
import { StarComponent } from './shared/star.component';
import { ProductService } from './products/prodduct.service';
import { NotFoundComponent } from './shared/notFound.component';
import { OrderComponent } from './orders/order.component';
import { HomeComponent } from './home/home.component';
import { ProductDetailComponent } from './products/productDetail.component';
import { ProductModule } from './products/product.module';



@NgModule({
    // contain all the module
    imports: [
        BrowserModule,
        FormsModule,
        HttpModule,
        HttpClientModule,
        RouterModule.forRoot([
            {path: 'products', component: ProductComponent},
            {path: 'products/:id', component: ProductDetailComponent},
            {path: 'orders', component: OrderComponent},
            {path: 'home', component: HomeComponent},
            {path: '', redirectTo: 'home', pathMatch: 'full'},
            {path: '**', component: NotFoundComponent},
        ]),
        ProductModule
    ],
    // All the component & pipe
    declarations: [
        AppComponent,
        DashComponent,
        ProductComponent,
        MyUpperPipe,
        AddValue,
        ProductFilter,
        StarComponent,
        NotFoundComponent,
        OrderComponent,
        HomeComponent,
        ProductDetailComponent
    ],
    // Only first/Main component
    bootstrap: [
        AppComponent
    ],
    // All Services are declare here
    providers: [
        ProductService
    ]
})

export class AppModule {

}
